import "oaidl.idl";
import "ocidl.idl";
import "ShObjIdl.idl";

[
    uuid(F9C67657-FB97-4E1C-BE43-32F6239C1118),  // AppId
    version(1.0)
]
library ContextMenuLib
{
    importlib("stdole32.tlb");
    importlib("stdole32.tlb");

    [
        uuid(56F70501-4289-40B4-BBA6-C1EFE27138AD),  // CLSID
        helpstring("My Tauri2 Context Menu Command")
    ]
    coclass ContextMenuCommand
    {
        [default] interface IExplorerCommand;
    };
};
